// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mizarsmnrvmssrgymnfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pemFyc21ucnZtc3NyZ3ltbmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDAzMDAsImV4cCI6MjA2OTA3NjMwMH0.0yBPBQv2ycRvBozlkW1wsFiHQaxLgZFxgy-gZDQfBSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});